name: VTEducator
favicon: null
layout_spectrum: 0.2193497563712299
typography_spectrum: 0.9670881680212915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6351931190583855
  lightness: 0.7935305738355964
  saturation: 0.3054811672773212
  rhythmicContrast: 0.03997568739578128
purpose: []
