typography_spectrum: 0.84227
content_rating:
  adult: false
color:
  saturation: 0.4042553
  brandStrength: 0
  lightness: 0.5
  brandColors:
    - '#ffffff'
    - '#92bd3f'
    - '#729356'
    - '#426139'
    - '#c8de9f'
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6361702
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Jeff Badillo
logo: null
name: VT Educator
cta:
  bucket: null
  version: null
  domain: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/799b7d14-6f79-4fa6-b52e-70134b113069.png'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: VT  Educator
purpose: []
