typography_spectrum: 0.8659046969842166
content_rating:
  adult: false
color:
  saturation: 0.4042553
  brandStrength: 0
  lightness: 0.5
  brandColors:
    - '#ffffff'
    - '#92bd3f'
    - '#729356'
    - '#426139'
    - '#c8de9f'
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5474175109993666
analytics:
  twitter: null
  google: UA-59206840-2
  facebook: null
author:
  name: Jeff Badillo
  email: jbadillo@vteducator.com
  url: vteducator.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fb5f7855-c503-43fa-819a-ba10e6af563f.jpg
name: VT EDUCATOR
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Home
    url: 'http://vteducator.com'
    type: external
  - name: About
    id: 9f1b54c6-6ba2-4b1b-b619-a8507abb2f22
    type: content
  - name: Portfolio
    url: 'http://portfolio.vteducator.com/'
    type: external
  - name: '@Jeff_Badillo'
    url: 'https://twitter.com/Jeff_Badillo'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/79d99577-8185-4eb8-8fc8-245621b476e0.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: VT EDUCATOR
description: ''
purpose: []
