name: VT Educator
favicon: null
layout_spectrum: 0.88054
typography_spectrum: 0.91233
title: VT  Educator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#92bd3f'
    - '#729356'
    - '#426139'
    - '#c8de9f'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.3054811672773212
  rhythmicContrast: 0.5
purpose: []
