title: VT  Educator
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4042553
  brandStrength: 0
  lightness: 0.5
  brandColors:
    - '#ffffff'
    - '#92bd3f'
    - '#729356'
    - '#426139'
    - '#c8de9f'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: VT Educator
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.84227
layout_spectrum: 0.6361702
