name: VTEducator
favicon: null
layout_spectrum: 0.2193497563712299
typography_spectrum: 0.9670881680212915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4ccc8'
    - '#5a78c9'
    - '#272e3e'
    - '#764e64'
    - '#b298c8'
  brandStrength: 0.625
  lightness: 0.7935305738355964
  saturation: 0.3054811672773212
  rhythmicContrast: 0.03997568739578128
purpose: []
